version: '3'

services:

  timely-app:
    build: ./
    # volumes:
    #- ./target/timely:/opt//wlp//usr/servers/defaultServer/apps/timely.war
    ports:
      - 9080:9080
      - 9443:9443
    depends_on:
      - timely-db
  
  timely-db:
    image: postgres:10.4
    volumes:
      - ./timely-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
